repos:
- repo: local
  hooks:
    - id: sort-manual-mapped-mappings
      name: Sort Manual Mapped Mappings
      entry: poetry run python scripts/sort_mappings.py data/Mapped2Willow.json
      language: system
      pass_filenames: false
    - id: sort-manual-willow-mappings
      name: Sort Manual Willow Mappings
      entry: poetry run python scripts/sort_mappings.py data/Willow2Mapped.json
      language: system
      pass_filenames: false
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: pretty-format-json
      exclude: ^(data/Mapped2Willow\.json|data/Willow2Mapped\.json)$
      args:
        - "--autofix"
        - "--indent=2"