name: Pull Request Build

on:
  pull_request:
    branches: [
      "main",
    ]
    paths: [
      '.github/**',
      'Ontology.Mappings/**',
    ]

env: 
  DOTNET_VERSION: '6.x' 

jobs:
  build:
    uses: 'WillowInc/opendigitaltwins-tools/.github/workflows/Ontology_Mappings.yml@main'