name: Mapped.Ontologies Build

on:
  workflow_call:
    inputs:
      build-type:
        required: false
        type: string
      publish-package:
        required: false
        type: string
        default: false

env:
  BASE_VERSION: "0.1.0"
  POETRY_VERSION: '1.6.1'
  containerName: 'public'
  storageAccount: 'mappedontologies'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Set up poetry
      uses: abatilo/actions-poetry@v2.1.5
      with:
        poetry-version: "${{ env.POETRY_VERSION}}"

    - name: Install Dependencies with Poetry
      run: |
        poetry source add --priority=supplemental fury https://pypi.fury.io/mapped/
        poetry config http-basic.fury ${{ secrets.FURY_READ_TOKEN_PUBLIC }} NOPASS
        poetry install --only main

    - name: Generate Mappings
      run: poetry run python scripts/generate_mappings.py
    
    - name: Sort Mapped Mappings
      run: poetry run python scripts/sort_mappings.py Ontologies.Mappings/src/Mappings/v1/Mapped/Willow2Mapped.json

    - name: Sort Willow Mappings
      run: poetry run python scripts/sort_mappings.py Ontologies.Mappings/src/Mappings/v1/Willow/Mapped2Willow.json

    - name: Upload Mapped Mappings Artifact
      uses: actions/upload-artifact@v2
      with:
        name: mapped-mappings
        path: Ontologies.Mappings/src/Mappings/v1/Willow/Mapped2Willow.json

    - name: Upload Willow Mappings Artifact
      uses: actions/upload-artifact@v2
      with:
        name: willow-mappings
        path: Ontologies.Mappings/src/Mappings/v1/Mapped/Willow2Mapped.json

    - name: Upload Mapped Missing Mappings Artifact
      uses: actions/upload-artifact@v2
      with:
        name: mapped-missing-mappings
        path: scripts/output/mapped_missing_mappings.json

    - name: Upload Willow Missing Mappings Artifact
      uses: actions/upload-artifact@v2
      with:
        name: willow-missing-mappings
        path: scripts/output/willow_missing_mappings.json

    - name: Establish Versioning, Tags, and Labels
      id: vtl
      uses: mapped/action-vtl@latest
      with:
        baseVersion: ${{ env.BASE_VERSION }}
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Upload staging blobs
      run: |
        az storage blob upload \
          --container-name ${{ env.containerName }} \
          --file Ontologies.Mappings/src/Mappings/v1/Willow/Mapped2Willow.json \
          --name mappings/Mapped2Willow/test \
          --account-name ${{ env.storageAccount }} \
          --overwrite \
          --connection-string "${{ secrets.ONTOLOGY_BLOB_STORE_CONN_STR }}"

        az storage blob upload \
          --container-name ${{ env.containerName }} \
          --file Ontologies.Mappings/src/Mappings/v1/Mapped/Willow2Mapped.json \
          --name mappings/Willow2Mapped/test \
          --account-name ${{ env.storageAccount }} \
          --overwrite \
          --connection-string "${{ secrets.ONTOLOGY_BLOB_STORE_CONN_STR }}"

        sleep 10 # wait enough for the files to be available in the CDN, hopefully.


    - name: Restore dependencies
      shell: pwsh
      run: "& ./.github/workflows/scripts/restore.ps1"

    - name: Test
      shell: pwsh
      run: "& ./.github/workflows/scripts/test.ps1"

    - name: Build
      if: github.ref == 'refs/heads/main'
      shell: pwsh
      run: |
        "& ./.github/workflows/scripts/buildandpack.ps1 -config Release -publishPackage ${{ inputs.publish-package }} -nugetSecret '${{ secrets.NUGET_MAPPINGS_WILLOW_PUSH }}' -VERTUPLE ${{ steps.vtl.outputs.ver_semVerFourTupleNumeric }} -githubRepo ${{ github.repository }} -githubBranch ${{ github.ref }} -githubCommit ${{ github.sha }} -buildNumber ${{ steps.vtl.outputs.ver_buildNumber }}"
        echo "${{ inputs.publish-package}}"
        echo "${{ inputs.publish-package == 'True'}}"
        echo '${{ inputs.publish-package}} == "True"'
        echo 'testing'



    - name: Upload production blobs
      if: inputs.publish-package == "true"
      run: |
        az storage blob upload \
          --container-name ${{ env.containerName }} \
          --file Ontologies.Mappings/src/Mappings/v1/Willow/Mapped2Willow.json \
          --name mappings/Mapped2Willow/latest \
          --account-name ${{ env.storageAccount }} \
          --overwrite \
          --connection-string "${{ secrets.ONTOLOGY_BLOB_STORE_CONN_STR }}"

        az storage blob upload \
          --container-name ${{ env.containerName }} \
          --file Ontologies.Mappings/src/Mappings/v1/Mapped/Willow2Mapped.json \
          --name mappings/Willow2Mapped/latest \
          --account-name ${{ env.storageAccount }} \
          --overwrite \
          --connection-string "${{ secrets.ONTOLOGY_BLOB_STORE_CONN_STR }}"

