name: Trigger Package Generation

on:
  push:
    branches: [
      "main",
    ]
    paths: [
      '.github/**',
      'Ontology.Mappings/**',
    ]

env: 
  DOTNET_VERSION: '6.x' 

jobs:
  build:
    uses: './.github/workflows/Ontology_Mappings.yml'
    with:
      build-type: 'Main Official'
      publish-package: 'True'
    secrets: inherit
