name: Mapped.Ontologies Build

on:
  workflow_call:
    inputs:
      build-type:
        required: false
        type: string
      publish-package:
        required: false
        type: string
        default: 'False'

env:
  BASE_VERSION: "0.1.0"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: "read/write"
    steps:

    - uses: actions/checkout@v3


    - name: Establish Versioning, Tags, and Labels
      id: vtl
      uses: mapped/action-vtl@latest
      with:
        baseVersion: ${{ env.BASE_VERSION }}
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}

    - name: Test VTL
      run: echo ${{ steps.vtl.outputs.ver_semVerFourTupleNumeric }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      shell: pwsh
      run: "& ./.github/workflows/scripts/restore.ps1"

    - name: Build
      shell: pwsh
      run: "& ./.github/workflows/scripts/buildandpack.ps1 -publishPackage ${{ inputs.publish-package }} -nugetSecret '${{ secrets.GITHUB_TOKEN }}' -VERTUPLE ${{ steps.vtl.outputs.ver_semVerFourTupleNumeric }} -githubRepo ${{ github.repository }} -githubBranch ${{ github.ref }} -githubCommit ${{ github.sha }} -buildNumber ${{ steps.vtl.outputs.ver_buildNumber }}"

    - name: Test
      shell: pwsh
      run: "& ./.github/workflows/scripts/test.ps1"
