name: Pull Request Build

on:
  pull_request:
    branches: [
      "main",
    ]

env: 
  DOTNET_VERSION: '6.x' 

jobs:
  build:
    uses: './.github/workflows/Ontology_Mappings.yml'
    with: 
      publish-package: false
    secrets: inherit
