name: Run Diagnostics

on: push

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python version
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install and Configure Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install dependencies with Poetry
      run: |
        poetry install
    
    - name: List Directories
      run: |
        ls -a
      
    - name: Run the script
      run: python scripts/mapping_diagnostics/main.py

    - name: Upload gaps.json as artifact
      uses: actions/upload-artifact@v2
      with:
        name: gaps-artifact 
        path: gaps.json
