name: Run Diagnostics

on: push

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Set up poetry
      uses: abatilo/actions-poetry@v2.1.5

    - name: install poetry
      run: |
        poetry install

    - name: Run Mapping Diagnostics
      run: python scripts/mapping_diagnostics/main.py

    - name: Upload gaps.json as artifact
      uses: actions/upload-artifact@v2
      with:
        name: gaps-artifact 
        path: gaps.json
