name: Pull Request Build

on:
  workflow_run:
    workflows: ["Ontology Mapper"]
    types: 
      - completed
  pull_request:
    branches: [
      "main",
    ]
    paths: [
      '.github/**',
      'Ontologies.Mappings/**',
    ]

env: 
  DOTNET_VERSION: '6.x' 

jobs:
  build:
    uses: './.github/workflows/Ontology_Mappings.yml'
    with: 
      publish-package: false
    secrets: inherit
